### ISSUE TITLE
Does this plugin support refresh token functionality?

### ISSUE THREAD

**Issue by xzetic05** [recognizegroup/capacitor-plugin-msauth#12]
We are interested to migrate on this plugin from our current auth plugin https://github.com/moberwasserlechner/capacitor-oauth2 as we are also using msauth similar to MSAL authentication. May we know if this plugin also support refreshing of token when accesstoken expired? Thank you!

**Comment by bartwesselink** [comment]
Hi @xzetic05, thank you for your interest in this plugin! When you invoke the `login()` method, this plugin will automatically determine whether it needs an interactive sign-in, or a silent sign-in. A silent sign-in will not be visible to the user and will refresh the access token, whereas the interactive sign-in will prompt the user for their account.

**Comment by cuzzlor** [comment]
That's what I've found to be the case (silent logins work after the initial login), we chain `login()` in front of our API calls IF the `accessToken` has expired.
