### ISSUE TITLE
Azure Active Directory B2C (Azure AD B2C)

### ISSUE THREAD

**Issue by Sampath-Lokuge** [recognizegroup/capacitor-plugin-msauth#4]
Hi,

Is this plugin supports `Azure Active Directory B2C (Azure AD B2C)` on both Android and iOS? Please let me know. Thanks!

If we need to get the user's email how can we do that using this plugin?

**Comment by bartwesselink** [comment]
Yes, Azure B2C is supported! You can do so by passing an authority url like this (next to the default options):
```
{
  authorityUrl: 'https://<b2c instance>.b2clogin.com/<b2c instance>.onmicrosoft.com/<b2c flow>/',
}
```

If you have added the user's email as a claim in B2C, you can use the `idToken` in the login response to get the e-mail.

**Comment by Sampath-Lokuge** [comment]
Yes, this is exactly what I need. Thanks a lot!
